disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

line_length: 150
identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - i
    - j
